version: '3.3'

services:

  db:
    image: mysql:8.0
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: depart
      MYSQL_USER: niyaz
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root

#Подключаться к бд из application.properties и idea по этому адресу             - jdbc:mysql://192.168.99.100:3309/departments
